#!/usr/bin/env python3
"""Run a command in a pseudo-terminal and print what it wrote.

Usage: script/pty-run KEYS COMMAND [ARGS...]

Waits until the command goes quiet, types KEYS (may be empty, "\\r" means
Enter), waits again, then types "exit" and prints the output with terminal
escape sequences stripped. script/test uses it to drive interactive shells.
"""
import fcntl
import os
import pty
import re
import select
import struct
import sys
import termios
import time


def read_until_idle(fd, idle=1.5, limit=15.0):
    out = b""
    start = last = time.time()
    while time.time() - start < limit:
        ready, _, _ = select.select([fd], [], [], 0.1)
        if ready:
            try:
                chunk = os.read(fd, 65536)
            except OSError:
                break
            if not chunk:
                break
            out += chunk
            last = time.time()
        elif out and time.time() - last > idle:
            break
    return out


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    keys = sys.argv[1].replace("\\r", "\r")
    pid, fd = pty.fork()
    if pid == 0:
        os.execvp(sys.argv[2], sys.argv[2:])
    fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", 40, 120, 0, 0))

    out = read_until_idle(fd)
    if keys:
        os.write(fd, keys.encode())
        out += read_until_idle(fd)
    try:
        os.write(fd, b"exit\r")
        out += read_until_idle(fd, idle=0.5, limit=5.0)
    except OSError:
        pass
    try:
        os.kill(pid, 9)
    except ProcessLookupError:
        pass
    os.waitpid(pid, 0)

    text = out.decode(errors="replace")
    text = re.sub(r"\x1b\][^\x07\x1b]*(\x07|\x1b\\)|\x1b\[[0-9;?<>=]*[ -/]*[@-~]|\x1b[()][A-Z0-9]|\x1b[=>]|\r", "", text)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
