# Path for homebrew (/usr/local/[s]bin)
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/sbin:$PATH"
export PATH="$HOME/.deno:$PATH"
export PATH="$(pyenv root)/shims:$PATH"
export PATH="$HOME/dev/dotfiles/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/env:$PATH"
export BAZ_ENV_FILE="$HOME/bazaar/backend/.env"